---
- name: 'Create single VM on VMware Platform from template and add tag'
  hosts: 'all'
  connection: 'local'
  gather_facts: 'no'
  tasks:
    - name: VM create task
      community.vmware.vmware_guest:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}" 
        username: "{{ lookup('env', 'VMWARE_USER') }}" 
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        validate_certs: 'no'
        datacenter: '{{ datacenter_name | default() }}'
        cluster: '{{ cluster_name | default() }}'
        name: '{{ vm_name | default(change_me) }}'
        folder: 'POCansible/vms'
        template: '{{ vm_template | default() }}'
        state: 'poweredon'
        hardware: 
          memory_mb: '{{ memory_mb | default(4096) }}'
          num_cpus: '{{ cpu | default(2) }}'
          