---
- name: 'Create single VM on VMware Platform from template'
  hosts: 'localhost'
  connection: 'local'
  gather_facts: 'no'
  tasks:
    - name: VM create task
      community.vmware.vmware_guest:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}" 
        username: "{{ lookup('env', 'VMWARE_USER') }}" 
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        validate_certs: 'no'
        datacenter: '{{ datacenter_name | default("Retired Hosts") }}'
        esxi_hostname: '{{ esx_hostname | default("172.16.7.111") }}' 
#        cluster: '{{ cluster_name | default() }}'
        name: '{{ vm_name | default("change_me") }}'
        folder: '{{ folder_name | default("/") }}' #POCansible/vms
        template: '{{ vm_template | default("rhe8.4-raben_ansible_templete") }}'
        state: 'poweredon'
        hardware: 
          memory_mb: '{{ memory_mb | default(4096) }}'
          num_cpus: '{{ cpu | default(2) }}'
        networks:
          - name: '{{ vm_net_name | default("Dev Servers Network") }}'
            ip: '{{ vm_ip | default("172.16.5.87") }}'
            netmask: '{{ vm_net_mask | default("255.255.255.0") }}'
            gateway: '{{ vm_net_gateway | default("172.16.5.1") }}'
            start_connected: true
        wait_for_ip_address: 'yes'
